title: Treehouse
subtitle: Total Points
name: Joe Sharp
url: https://teamtreehouse.com/joesharp
pie_colors:
  CSS: '#3659A2'
  HTML: '#3659A2'
  JavaScript: '#3659A2'
  API: '#008297'
  'C#': '#008297'
  Java: '#008297'
  PHP: '#008297'
  Python: '#008297'
  Ruby: '#008297'
  Design: '#4A4290'
  'Data Analysis': '#9F4B84'
  Databases: '#9F4B84'
  '21st Century Skills': '#9B3B5A'
  Business: '#9B3B5A'
  'Computer Science': '#9B3B5A'
  'Development Tools': '#9B3B5A'
  'Digital Literacy': '#9B3B5A'
  'Learning Resources': '#9B3B5A'
  'Quality Assurance': '#9B3B5A'
  Security: '#9B3B5A'
  Go: '#733A88'
  'Machine Learning': '#733A88'
  'Equity, Diversity, and Inclusion (EDI)': '#733A88'
  Android: '#30826C'
  iOS: '#30826C'
fallback_data:
  points:
    total: 19791
    Ruby: 3794
    JavaScript: 3128
    Python: 2688
    CSS: 1874
    Databases: 1441
    HTML: 1121
    Design: 951
    "Development Tools": 839
    Security: 776
    "Computer Science": 636
    "21st Century Skills": 441
    "Digital Literacy": 161
